[versions]
agp = "8.4.2"
accompanist = "0.34.0"
activity-compose = "1.9.0"
coil = "2.6.0"
com-google-devtools = "2.0.0-1.0.21"
compose = "1.7.0-beta02"
core-ktx = "1.13.1"
datastore = "1.1.1"
detekt = "1.23.6"
detekt-compose = "0.4.4"
fixture-monkey = "1.0.18"
kotest = "5.9.1"
kotlin = "2.0.0"
kotlinx-collections-immutable = "0.3.7"
kotlinx-coroutines = "1.8.1"
kotlinx-serialization-json = "1.7.0"
kover = "0.8.0"
ktfmt = "0.18.0"
lifecycle = "2.8.1"
material3 = "1.3.0-beta02"
media3-exoplayer = "1.3.1"
molecule-runtime = "2.0.0"
room-runtime = "2.7.0-alpha03"
turbine = "1.1.0"
vectordrawable = "1.2.0"
reorderable = "2.1.1"

[libraries]
accompanist-permissions = { module = "com.google.accompanist:accompanist-permissions", version.ref = "accompanist" }
activity-compose = { module = "androidx.activity:activity-compose", version.ref = "activity-compose" }
androidx-material-icons-extended = { module = "androidx.compose.material:material-icons-extended", version.ref = "compose" }
androidx-room-compiler = { module = "androidx.room:room-compiler", version.ref = "room-runtime" }
androidx-ui = { module = "androidx.compose.ui:ui", version.ref = "compose" }
androidx-ui-tooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "compose" }
coil = { module = "io.coil-kt:coil", version.ref = "coil" }
coil-compose = { module = "io.coil-kt:coil-compose", version.ref = "coil" }
core-ktx = { module = "androidx.core:core-ktx", version.ref = "core-ktx" }
datastore = { module = "androidx.datastore:datastore", version.ref = "datastore" }
fixture-monkey = { module = "com.navercorp.fixturemonkey:fixture-monkey-starter-kotlin", version.ref = "fixture-monkey" }
kotest-assertions-core = { module = "io.kotest:kotest-assertions-core", version.ref = "kotest" }
kotest-framework-datatest = { module = "io.kotest:kotest-framework-datatest", version.ref = "kotest" }
kotest-runner-junit5 = { module = "io.kotest:kotest-runner-junit5", version.ref = "kotest" }
kotlinx-collections-immutable = { module = "org.jetbrains.kotlinx:kotlinx-collections-immutable", version.ref = "kotlinx-collections-immutable" }
kotlinx-coroutines-guava = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-guava", version.ref = "kotlinx-coroutines" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinx-serialization-json" }
lifecycle-runtime-compose = { module = "androidx.lifecycle:lifecycle-runtime-compose", version.ref = "lifecycle" }
lifecycle-runtime-ktx = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycle" }
lifecycle-viewmodel-compose = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "lifecycle" }
lifecycle-viewmodel-ktx = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "lifecycle" }
compose-material3 = { module = "androidx.compose.material3:material3", version.ref = "material3" }
material3-window-size = { module = "androidx.compose.material3:material3-window-size-class", version.ref = "material3" }
media3-exoplayer = { module = "androidx.media3:media3-exoplayer", version.ref = "media3-exoplayer" }
media3-session = { module = "androidx.media3:media3-session", version.ref = "media3-exoplayer" }
molecule-runtime = { module = "app.cash.molecule:molecule-runtime", version.ref = "molecule-runtime" }
room-ktx = { module = "androidx.room:room-ktx", version.ref = "room-runtime" }
room-runtime = { module = "androidx.room:room-runtime", version.ref = "room-runtime" }
turbine = { module = "app.cash.turbine:turbine", version.ref = "turbine" }
vectordrawable = { module = "androidx.vectordrawable:vectordrawable", version.ref = "vectordrawable" }
detekt-compose = { module = "io.nlopez.compose.rules:detekt", version.ref = "detekt-compose" }
reorderable = { module = "sh.calvin.reorderable:reorderable", version.ref = "reorderable" }

[plugins]
com-android-application = { id = "com.android.application", version.ref = "agp" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt" }
kover = { id = "org.jetbrains.kotlinx.kover", version.ref = "kover" }
ktfmt = { id = "com.ncorti.ktfmt.gradle", version.ref = "ktfmt" }
org-jetbrains-kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
org-jetbrains-kotlin-plugin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
com-google-devtools-ksp = { id = "com.google.devtools.ksp", version.ref = "com-google-devtools" }
org-jetbrains-kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }

[bundles]
testing = [
    "fixture-monkey",
    "kotest-assertions-core",
    "kotest-framework-datatest",
    "kotest-runner-junit5",
    "turbine",
]

