[versions]
agp = "8.1.0-rc01"
accompanist = "0.31.5-beta"
activity-compose = "1.8.0-alpha06"
androidx-core = "1.5.0"
androidx-core-ktx = "1.5.0"
coil = "2.4.0"
constraintlayout-compose = "1.1.0-alpha09"
core = "1.6.0-alpha01"
core-ktx = "1.12.0-alpha05"
datastore-preferences = "1.0.0"
compose-destinations = "1.9.50"
gradle = "8.1.0-rc01"
hilt = "2.47"
hilt-navigation-compose = "1.0.0"
junit = "4.13.2"
kotlin = "1.8.22"
compose-compiler = "1.4.8"
compose = "1.6.0-alpha01"
kotlin-test = "1.8.22"
kotlinx-collections-immutable = "0.3.5"
kotlinx-coroutines-guava = "1.7.2"
kotlinx-serialization-json = "1.5.1"
lifecycle-viewmodel-ktx = "2.6.1"
material-3 = "1.1.1"
material-icons-extended = "1.6.0-alpha01"
media3-exoplayer = "1.1.0"
mockk = "1.13.5"
recyclerview = "1.3.0"
room-runtime = "2.6.0-alpha02"
ui-test-manifest = "1.6.0-alpha01"
vectordrawable = "1.1.0"
com-google-devtools = "1.8.22-1.0.11"


[libraries]
accompanist-permissions = { module = "com.google.accompanist:accompanist-permissions", version.ref = "accompanist" }
activity-compose = { module = "androidx.activity:activity-compose", version.ref = "activity-compose" }
androidx-material-icons-extended = { module = "androidx.compose.material:material-icons-extended", version.ref = "material-icons-extended" }
androidx-room-compiler = { module = "androidx.room:room-compiler", version.ref = "room-runtime" }
androidx-ui = { module = "androidx.compose.ui:ui", version.ref = "ui-test-manifest" }
androidx-ui-test-junit4 = { module = "androidx.compose.ui:ui-test-junit4", version.ref = "ui-test-manifest" }
androidx-ui-tooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "ui-test-manifest" }
coil = { module = "io.coil-kt:coil", version.ref = "coil" }
coil-compose = { module = "io.coil-kt:coil-compose", version.ref = "coil" }
compose-destinations-animations-core = { module = "io.github.raamcosta.compose-destinations:animations-core", version.ref = "compose-destinations" }
compose-destinations-ksp = { module = "io.github.raamcosta.compose-destinations:ksp", version.ref = "compose-destinations" }
constraintlayout-compose = { module = "androidx.constraintlayout:constraintlayout-compose", version.ref = "constraintlayout-compose" }
core = { module = "androidx.test:core", version.ref = "core" }
hilt-compiler = { module = "com.google.dagger:hilt-compiler", version.ref = "hilt" }
mockk = { module = "io.mockk:mockk", version.ref = "mockk" }
test-core = { module = "androidx.test:core", version.ref = "androidx-core" }
core-ktx = { module = "androidx.core:core-ktx", version.ref = "core-ktx" }
datastore = { module = "androidx.datastore:datastore", version.ref = "datastore-preferences" }
datastore-preferences = { module = "androidx.datastore:datastore-preferences", version.ref = "datastore-preferences" }
hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "hilt" }
hilt-navigation-compose = { module = "androidx.hilt:hilt-navigation-compose", version.ref = "hilt-navigation-compose" }
junit = { module = "junit:junit", version.ref = "junit" }
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin-test" }
kotlinx-collections-immutable = { module = "org.jetbrains.kotlinx:kotlinx-collections-immutable", version.ref = "kotlinx-collections-immutable" }
kotlinx-coroutines-guava = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-guava", version.ref = "kotlinx-coroutines-guava" }
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlinx-coroutines-guava" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinx-serialization-json" }
lifecycle-runtime-compose = { module = "androidx.lifecycle:lifecycle-runtime-compose", version.ref = "lifecycle-viewmodel-ktx" }
lifecycle-runtime-ktx = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycle-viewmodel-ktx" }
lifecycle-viewmodel-compose = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "lifecycle-viewmodel-ktx" }
lifecycle-viewmodel-ktx = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "lifecycle-viewmodel-ktx" }
compose-material3 = { module = "androidx.compose.material3:material3", version.ref = "material-3" }
material3-window-size = { module = "androidx.compose.material3:material3-window-size-class", version.ref = "material-3" }
media3-exoplayer = { module = "androidx.media3:media3-exoplayer", version.ref = "media3-exoplayer" }
media3-session = { module = "androidx.media3:media3-session", version.ref = "media3-exoplayer" }
recyclerview = { module = "androidx.recyclerview:recyclerview", version.ref = "recyclerview" }
room-ktx = { module = "androidx.room:room-ktx", version.ref = "room-runtime" }
room-runtime = { module = "androidx.room:room-runtime", version.ref = "room-runtime" }
test-core-ktx = { module = "androidx.test:core-ktx", version.ref = "androidx-core-ktx" }
ui-test-manifest = { module = "androidx.compose.ui:ui-test-manifest", version.ref = "ui-test-manifest" }
vectordrawable = { module = "androidx.vectordrawable:vectordrawable", version.ref = "vectordrawable" }

[plugins]
com-android-application = { id = "com.android.application", version.ref = "agp" }
org-jetbrains-kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
org-jetbrains-kotlin-plugin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
com-google-dagger-hilt-android = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }
org-jetbrains-kotlin-kapt = { id = "org.jetbrains.kotlin.kapt", version.ref = "kotlin" }
com-google-devtools-ksp = { id = "com.google.devtools.ksp", version.ref = "com-google-devtools" }
org-jetbrains-kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
org-jetbrains-kotlin-parcelize = { id = "org.jetbrains.kotlin.plugin.parcelize", version.ref = "kotlin" }

[bundles]

