package com.sebastianvm.musicplayer.designsystem.theme

import androidx.compose.ui.graphics.Color

object Color {
    val mdThemeLightPrimary = Color(0xFF176d0e)
    val mdThemeLightOnPrimary = Color(0xFFffffff)
    val mdThemeLightPrimaryContainer = Color(0xFFa0f88a)
    val mdThemeLightOnPrimaryContainer = Color(0xFF002200)
    val mdThemeLightSecondary = Color(0xFF54634d)
    val mdThemeLightOnSecondary = Color(0xFFffffff)
    val mdThemeLightSecondaryContainer = Color(0xFFd7e8cd)
    val mdThemeLightOnSecondaryContainer = Color(0xFF121f0e)
    val mdThemeLightTertiary = Color(0xFF386669)
    val mdThemeLightOnTertiary = Color(0xFFffffff)
    val mdThemeLightTertiaryContainer = Color(0xFFbcebee)
    val mdThemeLightOnTertiaryContainer = Color(0xFF002022)
    val mdThemeLightError = Color(0xFFba1b1b)
    val mdThemeLightErrorContainer = Color(0xFFffdad4)
    val mdThemeLightOnError = Color(0xFFffffff)
    val mdThemeLightOnErrorContainer = Color(0xFF410001)
    val mdThemeLightBackground = Color(0xFFfcfcf6)
    val mdThemeLightOnBackground = Color(0xFF1a1c19)
    val mdThemeLightSurface = Color(0xFFfcfcf6)
    val mdThemeLightOnSurface = Color(0xFF1a1c19)
    val mdThemeLightSurfaceVariant = Color(0xFFdee4d7)
    val mdThemeLightOnSurfaceVariant = Color(0xFF43493f)
    val mdThemeLightOutline = Color(0xFF73796e)
    val mdThemeLightInverseOnSurface = Color(0xFFf1f1eb)
    val mdThemeLightInverseSurface = Color(0xFF2f312d)

    val mdThemeDarkPrimary = Color(0xFF85db71)
    val mdThemeDarkOnPrimary = Color(0xFF003a00)
    val mdThemeDarkPrimaryContainer = Color(0xFF005300)
    val mdThemeDarkOnPrimaryContainer = Color(0xFFa0f88a)
    val mdThemeDarkSecondary = Color(0xFFbbcbb2)
    val mdThemeDarkOnSecondary = Color(0xFF273422)
    val mdThemeDarkSecondaryContainer = Color(0xFF3d4b37)
    val mdThemeDarkOnSecondaryContainer = Color(0xFFd7e8cd)
    val mdThemeDarkTertiary = Color(0xFFa0cfd2)
    val mdThemeDarkOnTertiary = Color(0xFF00373a)
    val mdThemeDarkTertiaryContainer = Color(0xFF1e4d50)
    val mdThemeDarkOnTertiaryContainer = Color(0xFFbcebee)
    val mdThemeDarkError = Color(0xFFffb4a9)
    val mdThemeDarkErrorContainer = Color(0xFF930006)
    val mdThemeDarkOnError = Color(0xFF680003)
    val mdThemeDarkOnErrorContainer = Color(0xFFffdad4)
    val mdThemeDarkBackground = Color(0xFF1a1c19)
    val mdThemeDarkOnBackground = Color(0xFFe2e3dc)
    val mdThemeDarkSurface = Color(0xFF1a1c19)
    val mdThemeDarkOnSurface = Color(0xFFe2e3dc)
    val mdThemeDarkSurfaceVariant = Color(0xFF43493f)
    val mdThemeDarkOnSurfaceVariant = Color(0xFFc3c9bc)
    val mdThemeDarkOutline = Color(0xFF8d9387)
    val mdThemeDarkInverseOnSurface = Color(0xFF1a1c19)
    val mdThemeDarkInverseSurface = Color(0xFFe2e3dc)

    val error = Color(0xFFba1b1b)
}
