name: Android CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build project and run JVM unit tests.
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build

  instrumented-test:
    name: Instrumented Unit tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        api-level: [ 29, 31 ]

    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle
      - name: run tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          target: 'google_apis'
          api-level: ${{ matrix.api-level }}
          arch: "x86_64"
          script: ./gradlew connectedCheck
