name: Android CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  setup:
    name: Check out project and setup Java.
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: "temurin"
          cache: gradle
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Run ktfmt check
        run: ./gradlew ktfmtCheck
      - name: Run lint
        run: ./gradlew lint
      - name: Run detekt on main sources
        run: ./gradlew detektMain
      - name: Run detekt on test sources
        run: ./gradlew detektTest
      - name: Run tests
        run: ./gradlew test