name: Android CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  setup:
    name: Check out project and setup Java.
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: "temurin"
          cache: gradle
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

  ktfmtCheck:
    name: Run ktfmt check
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - run: ./gradlew ktfmtCheck

  build:
    name: Build app
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - run: ./gradlew assemble

  lint:
    name: Run lint
    needs: build
    runs-on: ubuntu-latest
    steps:
      - run: ./gradlew lint

  detektMain:
    name: Run detekt on main sources
    needs: build
    runs-on: ubuntu-latest
    steps:
      - run: ./gradlew detektMain

  detektTest:
    name: Run detekt on test sources
    needs: build
    runs-on: ubuntu-latest
    steps:
      - run: ./gradlew detektTest

  tests:
    name: Run tests
    needs: build
    runs-on: ubuntu-latest
    steps:
      - run: ./gradlew test