name: Android CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build project and run JVM unit tests.
    runs-on: ubuntu-latest

    steps:
      - run: echo "running" # Adding this so I stop getting emails about failed workflows while I fix tests
      - uses: actions/checkout@v4
      - name: set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Run checks
        run: ./gradlew check