name: Gradle Dependency Submission

on:
  push:
    branches:
      - main

jobs:
  dependency-submission:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project sources
        uses: actions/checkout@v4
      - name: set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: "temurin"
          cache: gradle

      - name: Generate and submit dependency graph
        uses: gradle/actions/dependency-submission@v3
        with:
          build-scan-publish: true
          build-scan-terms-of-use-url: "https://gradle.com/terms-of-service"
          build-scan-terms-of-use-agree: "yes"
        env:
          # Exclude all dependencies that originate solely in the 'buildSrc' project
          DEPENDENCY_GRAPH_EXCLUDE_PROJECTS: ':'
          # Exclude dependencies that are only resolved in test classpaths
          DEPENDENCY_GRAPH_EXCLUDE_CONFIGURATIONS: '.*[Tt]est(Compile|Runtime)Classpath'