package com.sebastianvm.musicplayer.ui.theme

import androidx.compose.ui.graphics.Color

val md_theme_light_primary = Color(0xFF176d0e)
val md_theme_light_onPrimary = Color(0xFFffffff)
val md_theme_light_primaryContainer = Color(0xFFa0f88a)
val md_theme_light_onPrimaryContainer = Color(0xFF002200)
val md_theme_light_secondary = Color(0xFF54634d)
val md_theme_light_onSecondary = Color(0xFFffffff)
val md_theme_light_secondaryContainer = Color(0xFFd7e8cd)
val md_theme_light_onSecondaryContainer = Color(0xFF121f0e)
val md_theme_light_tertiary = Color(0xFF386669)
val md_theme_light_onTertiary = Color(0xFFffffff)
val md_theme_light_tertiaryContainer = Color(0xFFbcebee)
val md_theme_light_onTertiaryContainer = Color(0xFF002022)
val md_theme_light_error = Color(0xFFba1b1b)
val md_theme_light_errorContainer = Color(0xFFffdad4)
val md_theme_light_onError = Color(0xFFffffff)
val md_theme_light_onErrorContainer = Color(0xFF410001)
val md_theme_light_background = Color(0xFFfcfcf6)
val md_theme_light_onBackground = Color(0xFF1a1c19)
val md_theme_light_surface = Color(0xFFfcfcf6)
val md_theme_light_onSurface = Color(0xFF1a1c19)
val md_theme_light_surfaceVariant = Color(0xFFdee4d7)
val md_theme_light_onSurfaceVariant = Color(0xFF43493f)
val md_theme_light_outline = Color(0xFF73796e)
val md_theme_light_inverseOnSurface = Color(0xFFf1f1eb)
val md_theme_light_inverseSurface = Color(0xFF2f312d)

val md_theme_dark_primary = Color(0xFF85db71)
val md_theme_dark_onPrimary = Color(0xFF003a00)
val md_theme_dark_primaryContainer = Color(0xFF005300)
val md_theme_dark_onPrimaryContainer = Color(0xFFa0f88a)
val md_theme_dark_secondary = Color(0xFFbbcbb2)
val md_theme_dark_onSecondary = Color(0xFF273422)
val md_theme_dark_secondaryContainer = Color(0xFF3d4b37)
val md_theme_dark_onSecondaryContainer = Color(0xFFd7e8cd)
val md_theme_dark_tertiary = Color(0xFFa0cfd2)
val md_theme_dark_onTertiary = Color(0xFF00373a)
val md_theme_dark_tertiaryContainer = Color(0xFF1e4d50)
val md_theme_dark_onTertiaryContainer = Color(0xFFbcebee)
val md_theme_dark_error = Color(0xFFffb4a9)
val md_theme_dark_errorContainer = Color(0xFF930006)
val md_theme_dark_onError = Color(0xFF680003)
val md_theme_dark_onErrorContainer = Color(0xFFffdad4)
val md_theme_dark_background = Color(0xFF1a1c19)
val md_theme_dark_onBackground = Color(0xFFe2e3dc)
val md_theme_dark_surface = Color(0xFF1a1c19)
val md_theme_dark_onSurface = Color(0xFFe2e3dc)
val md_theme_dark_surfaceVariant = Color(0xFF43493f)
val md_theme_dark_onSurfaceVariant = Color(0xFFc3c9bc)
val md_theme_dark_outline = Color(0xFF8d9387)
val md_theme_dark_inverseOnSurface = Color(0xFF1a1c19)
val md_theme_dark_inverseSurface = Color(0xFFe2e3dc)

val seed = Color(0xFF026100)
val error = Color(0xFFba1b1b)